# Generated by Django 3.1.7 on 2021-03-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_remove_gccontent_gcper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gccontent',
            name='gcseq',
        ),
        migrations.AddField(
            model_name='gccontent',
            name='gcseq',
            field=models.ManyToManyField(to='first_app.Seq'),
        ),
    ]
