# Generated by Django 3.1.7 on 2021-03-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20210302_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='gccontent',
            name='GCPer',
            field=models.SmallIntegerField(null=True),
        ),
    ]
