# Generated by Django 3.1.3 on 2021-03-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_gccontent_gcper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GCcontent',
        ),
    ]
