# Generated by Django 3.1.3 on 2021-03-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20210306_1818'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seq',
            table='Seq',
        ),
    ]
