# Generated by Django 3.1.3 on 2021-03-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20210306_1854'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seq',
            table=None,
        ),
    ]
